### ISSUE TITLE
Not resolving .sass modules properly

### ISSUE THREAD

**Issue by mrjoelkemp** [dependents/node-sass-lookup#1]
All of these should pass:

```
@import styles2.sass
@import styles3
@import _styles3
```

Update readme when fixed

**Comment by alreece45** [comment]
@mrjoelkemp Is this still an issue? Could you provide more details on expected vs actual behavior?

**Comment by mrjoelkemp** [comment]
Will close since the issue hasn't come up since and I don't have details/context around the problem anymore.
