### ISSUE TITLE
Cannot process file names that contain `.` in the middle and no file extension

### ISSUE THREAD

**Issue by jpblancoder** [dependents/node-sass-lookup#6]
This resolver doesn't seem to be able to process a file name like this:

`@import "patterns/stylesheets/components.article-correction";`

Actual path: `patterns/stylesheets/_components.article-correction.sass`

Here is an example of an OOCSS framework that follows this directory structure, and file naming convention: https://github.com/inuitcss/inuitcss#css-directory-structure

**Comment by XhmikosR** [comment]
@jpblancoder your best bet is to add a failing test case, try to provide a PR and CC me.

I just released v4.0.0 which updates many things, but I'm pretty sure your issue is still present since it's probably not covered by tests.

**Comment by jpblancoder** [comment]
@XhmikosR The related Git repo I was having the issue with has been archived and I don't have access to it any longer, to duplicate the issue. I think you can just close this issue. Thank you.
